version: '3.8'

services:
  database:
    image: postgres:16  # Official PostgreSQL image
    container_name: library_db
    restart: always
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: library  # The name of your database
    ports:
      - "5432:5432"  # Exposing port for PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Ensure persistent data storage

  pgadmin:
    image: dpage/pgadmin4  # Official pgAdmin image
    container_name: library_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com  # Admin login email
      PGADMIN_DEFAULT_PASSWORD: postgres  # Admin login password
    ports:
      - "5050:80"  # Expose pgAdmin on port 5050
    depends_on:
      - database  # Ensure pgAdmin waits for PostgreSQL to start

  api:
    build: .
    container_name: library_api
    restart: always
    depends_on: 
      - database

    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5001
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=library;Username=sami;Password=123abc  # Update your connection string
    ports:
      - "5001:5001"  # Exposing API port

volumes:
  postgres_data:  # This ensures persistent database data storage
